Algolisted-Org/AlgoListed

src/Components/LeftMenu.js, src/index.css
=> scroll bar

package.json, src/Screen/CodingCompetitions.js
=> added dynamic time left functionality

src/Screen/CodingCompetitions.js
=> added implementation in registration table still some bugs need to be fixed

package-lock.json, src/Screen/CodingCompetitions.js, src/helpers/IntervalTimeLeft.js, src/helpers/TimeLeft.js, yarn.lock
I added two helpers components and corrected var variable declarations. The date changes every minute
=> update data every minute

src/Screen/CodingCompetitions.js
I added a filter to remove expired contests from the list
=> filter expired contests from the list

WantToContribute.md, client/src/Screen/CodingCompetitions.js, client/src/Screen/CompetitionItem.js, client/src/Screen/competitionFilters.js, client/yarn.lock, package-lock.json
- I took the liberty of moving the 'Competition list items' into its own component ( `CompetitionItem.js` ) , both to reduce the amount of JSX and to make the JSX structure and code a bit easier to read.
- Also moved the "filters" (the div buttons that the user clicks) to a simple separate file and imported them as an array, so they can be rendered by simply mapping through it, making it much easier to add logic without repeating code, going from a long JSX tree to simply `<Filters>{filters}</Filters>`.
- Probably forgot to do cleanup of a couple of functions (returnHours and returnMins) that I moved to the competition list-item component.
-Added myself to contributors
Feel free to point out if you want  me to make any modifications.
Ever since the first save and update that I did, I …
=> Filter competitions

client/src/Components/CompetitionItem.js, client/src/Screen/CodingCompetitions.js, client/src/helpers/IntervalTimeLeft.js, client/src/helpers/TimeLeft.js
I changed the remaining time calculator so that it counts to the minute
=> calculate the remaining time to the exact minute

client/src/Components/CompetitionItem.js, client/src/Screen/CodingCompetitions.js
Added a background color for contests that have expired but are still running
=> add background color for expired contests

client/package.json, client/src/index.js, client/src/redux/reducer/rootReducer.js, client/src/redux/store.js
#40 Add redux folder structure.
=> Redux setup

WantToContribute.md, client/src/Screen/LandingPage.js, client/src/Screen/LandingPageComponents/BottomMessage/BottomMessage.js, client/src/Screen/LandingPageComponents/Contributors/Contributors.js, client/src/Screen/LandingPageComponents/Footer/Footer.js, client/src/Screen/LandingPageComponents/Hero/Hero.js, client/src/Screen/LandingPageComponents/ModulesSection/ModuleSection.js, client/src/Screen/LandingPageComponents/OriginalLandingPage.js, client/src/Screen/LandingPageComponents/TopMessage/TopMessage.js
-So the first change I made was to break up the landing page into several components to make troubleshooting and to navigate the CSS much easier for me (The original landing page JS file is in `\Algorithmist\client\src\Screen\LandingPageComponents\OriginalLandingPage.js`
-There are some CSS I felt didn't serve a purpose after the changes and I commented them out, I left a comment next to the changes.
-Then I set up several media queries directly under where the classes were called in styled-components so my changes could be easily found.
=> Landing page mobile css

client/src/Screen/CodingCompetitions.js
I added the functionality of sorting by relevance along with a drop-down menu, and a dynamically changing button name
=> add sort by relevance functionality with drop-down menu

client/src/Screen/CodingCompetitions.js
I added conditions to sort according to the guidelines. Temporarily, sorting is based on the length of the contest, not the time left in the contest
=> add sorting condition temporarily for duration

client/package-lock.json, client/package.json, client/src/Screen/CodingSheets.js, client/yarn.lock
Added the ability to complete tasks, and a dynamic progress bar.
=> JordanAdair#47-CodingSheetsPage

client/src/Components/CompetitionItem.js, client/src/Screen/CodingCompetitions.js, client/src/helpers/TimeLeft.js, client/src/helpers/sortByContestTiming.js, client/src/helpers/sortByRegistration.js
I removed the random sorting option and set the sorting by contest time as the default. I also tidied up the code by extracting the sort functions to a helpers folder and destructuring the object
=> Sorting categories.4

client/src/Screen/CodingSheets.js
I felt like 0.25s looked nice, but feel free to change it as you see fit.
=> #58 Added an animation to the progress bar

client/package-lock.json, client/src/Screen/CodingCompetitions.js, client/src/Screen/CodingSheets.js, client/yarn.lock
Created Mobile Cards in the format suggested, although I feel like we could make these look a little better somehow. Would love to hear any suggestions.
I decided against the giant clickable field since it actually was kind of annoying. I'd try to scroll and would accidentally click it lol. 
Also, I can't figure out how to specifically target the content above the cards (filter, text, etc.) on mobile. I wanted to keep it in line with the cards, but I can't figure out how to "target" those with CSS.
=> #61 Created mobile cards

client/src/Screen/ChartTemp.js
Line 14 added  colors accordingly.
=> Add colors to charttemp doughnut

backend/Python Modules/Project 8 Coding Competitions/One Script Army/allContests.json, backend/Python Modules/Project 8 Coding Competitions/One Script Army/oneManArmy.py
contests including leetcode, codechef, codeforces, atcoder
=> Added ultimate script to scrape all contests

backend/package-lock.json, client/package-lock.json, client/src/App.js, client/src/Screen/Contact.js, client/src/Screen/FutureVision.js, client/src/Screen/LandingPage2.js, client/src/Screen/Mission.js, client/src/Screen/RequestAPI.js, client/src/Screen/index.js, client/yarn.lock
1. I added the following links
- About us
- Team
- Our Mission 
- Contact
- Future Vision
- Login
- Create account
- Request API access
2. I created the following demo screen components
- Contact
- Mission
- FutureVision
- RequestAPI
3. There were too many import statements in the App.js. Therefore, I created an `index.js` file in `Screen/index.js` and moved those imports to that file.
4.  Therefore in the future, you can add any imports to `App.js` from  Screen to the `Screen/index.js` .
**Recommendation**: I suggest you implement the same strategy for the Components folder as you will have many import statements in App.js from the Components folder in the future.
=> Enter proper links in Landing Page Footer

client/README.md, package-lock.json
this readme file consists of guide for installation of the project.
=> add readme for installation

client/src/Components/CompetitionItem.js, client/src/helpers/TimeLeft.js
fix the name conflict bug regarding the start time of the competition
=> fix the name conflict bug regarding the start time of the competition

client/src/Components/contributorsData.json, client/src/Screen/ContributorWork.js
https://github.com/Nayaker/AlgoListed/assets/7922315/fce8c3ec-d53d-4cb5-94ab-7dcd44229b03
Have tried to match the UI with other pages of the website to achieve a consistent look across all pages.
=> # 101 Issue Resolved |  Added contributor data and updated UI on contributor-work page

client/src/Screen/ContestAnalysis.js
=> Contest analysis page UI updated

client/src/Screen/showdownServer.js
=> bug:correct css in showdownserver

client/src/App.js, client/src/MicroComponents/Allmodals/AddfriendModal.jsx, client/src/MicroComponents/input.jsx, client/src/Screen/ContestAnalysis.js
Reverts Nayaker/AlgoListed#123
=> Revert "bug:code-analysis"

client/src/Screen/ContestArchive.js
=> Update ContestArchive.js to Fetch Data from LcContests.json #135

client/package-lock.json, client/src/App.js, client/src/Screen/Resources.js, client/src/dark_mode_colors_resources.css, client/yarn.lock
###waht changes does this PR introduce?
This PR create dark mode feature in resourses page 
Fixes #110
=> Dark mode feature added  in resourse page

client/src/Screen/LandingPage3.js
=> Added relevant text in Features section in Home page

client/src/Screen/ContestArchive.js
Hello,
This pull request attempts to fix Issue #165. 
- I have added a Stacked bar chart that represents the number of problems (type A, B, C or D) under each tag.
- I have also made the close visualisation button functional with a small sliding up/down animation.
=> #165 Issue Resolved | Stacked Bar chart added in the Contest Archive Page

client/src/Screen/CodingSheets.js, package-lock.json, package.json
=> [bug]:bug-solved

client/src/MicroComponents/Tagsfilter.jsx, client/src/MicroComponents/searchbar.jsx, client/src/Screen/CodingSheets.js
=> changes done

client/src/MicroComponents/Tagsfilter.jsx, client/src/Screen/CodingSheets.js
Changed the UI for filters and fixed the filters that weren't working properly before.
Closes #190
=> Fixed filters in coding sheets

client/src/Screen/ContestAnalysis.js, client/src/Screen/ContestArchive.js
Hello,
The pull request attempts to resolve #191.
I have also added custom legends in the contest analysis page instead of those built-in in the charts since I thought they look better and all the graphs would have uniform legends. Please let me know if you prefer the previous ones, I'll revert them!
=> Issue #191 Resolved | Dark mode added for graphs

client/src/Screen/CodingSheets.js
=> Added stopwatch functionality

client/src/Screen/CoreSubjectsTracker.js
For #200 
Task 2.1 completed: Added the functionality to hide/show the answer.
Progress bar for questions also made functional, please check and confirm if any changes required so far.
Will continue pushing to the same branch for further updates in the issue.
=> CST-Questions functionality updated

client/src/Screen/ResumeSection.js
Hello, 
This pull request attempts to resolve #212. I have added keys 'atsScoreValue', 'grammer','impact' to the state object variable 'dummyResponse' and used their values for plotting the graphs. Hope I got that right!
=> Issue #212 Resolved | Added charts in the Resume Questions Page

client/src/Components/CCHeaderDarkPlus.js, client/src/MicroComponents/Tagsfilter.jsx, client/src/Screen/CodingSheets.js
refactored and optimized code for the coding sheet and also cleared all the console errors
closes #202
=> Cleaned codingsheets.js

client/src/Screen/CoreSubjectsTracker.js
- refer  @Nayaker 
solved
marked
=> create filter for core subjects tracker page

client/src/Screen/Opportunities.js
In this commit I am proposing some changes to add feature of filtering opportunities based on type of position, experience and more.
Closes: #217 
@Nayaker, Please have a look at changes.
If you are fine with this approach, I will finish remaining changes for filter options.
=> Filtering Opportunities: Proposal

client/src/Screen/Opportunities.js
This pull request addresses the sub-task mentioned in issue #217.
- Added logic for location filter in the filtering opportunities.
- Added logic for location filter in the filtering options.
- Implemented an API call to determine if job opportunities are in India or outside India.
- Enhanced the filtering functionality by introducing a location filter.
- The new location filter allows users to specify their preference for job opportunities based on location.
- Integrated an API call to fetch all cities of a given country, specifically targeting India.
- Used the fetched cities data to determine if a job opportunity is located in India or outside India.
- The location filter now considers this information to provide more accurate filtering options.
Filtering Options
[x]Location
[] Status …
=>  added location filters to opportunities #225 Issue Resolved

client/src/Screen/Opportunities.js
=> Remove redundant code

client/src/DummyDB/CoreSubjects/DBMSquestions.json
Sample Questions added for testing
=> 10 DBMS Questions added

client/src/DummyDB/CoreSubjects/CNquestions.json, client/src/DummyDB/CoreSubjects/DBMSquestions.json
Top 20 frequently asked questions on DBMS and CN added for reference before interviews. :)
=> DBMS and CN questions added in the CoreTracker

client/src/Screen/ContributorWork.js
PR height fixed on contributor page
=> contributor work page height fixed

client/src/Screen/MockAssessment.js, client/src/Screen/MockAssessmentRunning.js
=> mock assessment part 1 completed

client/src/Screen/Opportunities.js
This PR gives a partial fix to issue #225
1. Fixed a small bug in Opportunity Type filter by replacing '===' with '.includes()'
2. Rewrote the experience filter logic to handle all cases properly.
3. The location filter had been searching for "All Location" and the actual value was "All Locations", small type fixed.
Comments have been included at relevant places.
=> Partial Fix for Issue #225 - Fixed Bugs in Job Type and Fresher filters

client/package-lock.json, client/src/Screen/Opportunities.js, client/yarn.lock
This PR finally solves Issue #225 
1. Changed the handling of Opportunities Data, from useState to useReducer
2. Implemented status handling, basic UI implemented
3. Implemented status filtering
Comments have been included at relevant places.
=> Issue #225 Resolved - Finished with Status handling

client/package-lock.json, client/package.json, client/src/Screen/Opportunities.js, client/yarn.lock
This pull request introduces functionality to track the status of three buttons ("Filled," "Not Interested," and "Liked") using `localStorage`.
=> feat: implement localStorage for button status tracking

client/src/Screen/LandingPage2.js
#260 Have made the appropriate changes.
=> Profile links working fine

client/src/App.js, client/src/Screen/CommingSoon.js, client/src/Screen/PageNotExist.js, client/yarn.lock
#258 Issue solved
This pull request updates the "Page Not Found" page to enhance user experience and provide clearer navigation options.
The previous error message has been replaced with a more user-friendly notification. The new message now reads:
**"Feature will be soon available."**
=> Update: Updated the PageNotExist 

client/src/Screen/Opportunities.js
Added a visual separator line between the Opportunity and Track columns .
=> fix: Add missing line between Opportunity and Track in Table

client/src/Components/LeftMenu.js, client/src/Components/LeftMenuDark.js, client/src/Components/OILeftMenu.js
Fixes: #274 
https://github.com/user-attachments/assets/d5cfc00e-15fa-4693-9677-bc71abf98fa2
=> Fix: Clicking the icon does not redirect to the home page

client/src/Screen/LandingPage2.js, package-lock.json
=> updated footer socials links and corrected spelling of connect in Connect with us

client/src/Screen/Contributors.js, client/src/Screen/LandingPage2.js
=> Improve contributor section

backend/index.js
Fixed #289 
These changes should help improve the performance and security of your application.
1. Using Compression Middleware
Compressing responses can significantly reduce the size of the data sent over the network.
2. Optimize CORS Configuration
Ensure that CORS is configured only for necessary routes to minimize overhead.
3. Use async/await for MongoDB Connection
This can make your code cleaner and easier to read.
4. Use a Connection Pool for MongoDB
Ensure that you are using connection pooling to manage database connections more efficiently.
5. Limit Middleware Usage
Only use middleware that is necessary for each route to reduce processing time.
6. Implement Rate Limiting
To prevent abuse and ensure fair usage of your API.
7. Use helmet for Security
This helps secure your Express …
=> Fixed: Improved the performance of express application and Security
